apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: production-rabbitmqcluster
spec:
  replicas: 2
  persistence:
    storage: 11Gi
  resources:
    requests:
      cpu: 200m
      memory: 100Mi
    limits:
      cpu: 1
      memory: 500Mi
  rabbitmq:
          additionalConfig: |
                  log.console.level = info
                  channel_max = 1700
                  default_user= admin 
                  default_pass = secpasswd
                  default_user_tags.administrator = true
  service:
    type: ClusterIP